plugin:
  name: custom-data-type-gnd
  version: 1.0
  server:
    api-version:
      require: 1
  webfrontend:
    url: build/webfrontend/custom-data-type-gnd.js
    l10n: build/webfrontend/l10n/
custom_types:
  gnd:
    elasticsearch:
      mapping:
        type: object
        properties:
          conceptName:
            type: string
            index: no
            fields:
              exact:
                type: string
                term_vector: with_positions_offsets
                analyzer: ez_exact_analyzer
              folded:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_folded_analyzer
              fulltext:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_fulltext_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              phrase:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_phrase_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              sort:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: sort_de-DE
              suggest:
                type: string
                term_vector: with_positions_offsets
                index_analyzer: ez_text_suggest_analyzer
              token:
                type: string
                term_vector: with_positions_offsets
                analyzer: ez_text_token_analyzer
    config:
      schema:
        - name: add_differentiatedpersons
          parameters:
            value:
              type: bool
        - name: add_coorporates
          parameters:
            value:
              type: bool
        - name: add_geographicplaces
          parameters:
            value:
              type: bool
        - name: add_subjects
          parameters:
            value:
              type: bool
      mask:
        - name: show_infopopup
          parameters:
            value:
              type: bool
